Update docker file to support ENABLE_WEBDAV_SECRET
ggogel/seafile-containerized pull request #43
Opened 2022-03-26 20:48 UTC by dervomsee

When 2FA login is activated, webdav does not work, because it does not support 2FA.
The option ENABLE_WEBDAV_SECRET enables a additional secret for WebDAV login.
This feature needs pycryptodome.

Without the pip module the login fails and the following error is generated:
`seafile-server_1     | 2022-03-26 21:13:14.506 - <140120687240960> wsgidav.dc.domain_controller WARNING :  Failed to login: No module named 'Crypto'`
The module is needed here: https://github.com/haiwen/seafdav/blob/02d153ff1a292b55e264b92e88a25b9f024c1f98/wsgidav/dc/domain_controller.py#L132

2022-03-26 21:33 UTC, ggogel requested changes

2022-03-26 21:33 UTC, ggogel commented on seafile-server/Dockerfile
> +RUN python3 -m pip install --upgrade pip &&\
I'd just add the ubuntu package `python3-pycryptodome`. Like this, we will also get the most recent version.

2022-03-26 21:43 UTC, dervomsee commented on seafile-server/Dockerfile
> +RUN python3 -m pip install --upgrade pip &&\
You're right. That's better.

2022-03-26 21:45 UTC, ggogel approved these changes

2022-03-26 21:45 UTC, merged

2022-03-26 22:22 UTC, dervomsee commented
Hmm, very strange.
With the pip package it work (regardless of the version), with the Ubuntu package not. With the Ubuntu package i still get the following.
`seafile-server_1     | 2022-03-26 23:19:06.109 - <140291192919808> wsgidav.dc.domain_controller WARNING :  Failed to login: No module named 'Crypto'`

@ggogel Do you have a idea, why this makes a difference?

2022-03-26 23:53 UTC, ggogel commented
Looks like the package is in fact installing `pycryptodomex` instead of `pycryptodome` It installs the modules under `Cryptodome` instead of `Crypto`.  See https://pypi.org/project/pycryptodomex/
This was an easy fix
`cp -r  /usr/lib/python3/dist-packages/Cryptodome/  /usr/lib/python3/dist-packages/Crypto/`
I'll add it to the image.

2022-03-27 00:10 UTC, ggogel commented
For reference: f9c9a0cd039d6cf60c42140fd9025c84d0d60106

2022-03-28 19:12 UTC, dervomsee commented
I used the seafile-server-9.0.4_002 image and it workes.
Thx!